repos:
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.0
    hooks:
    - id: isort
-   repo: https://github.com/ambv/black
    rev: "23.1.0"
    hooks:
    - id: black
      language_version: python3.10
-   repo: https://github.com/PyCQA/autoflake 
    rev: v2.0.1
    hooks:
    - id: autoflake 
      entry: autoflake --remove-all-unused-imports --remove-unused-variables